version: '3.8'

services:
  flaskapp:
    container_name: flaskapp
    image: flaskapp:1.0.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

  db:
    container_name: db
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
