export const recipes = [
  {
    id: "1",
    author: "John Doe",
    date: "3 October, 2024",
    title: "Pizza Pasta Porsche",
    description: "Summer, Breezes, and you",
    level: "Easy",
    duration: "45 mins",
    calories: 600,
    image: "/demo/thumbnail.png",
    authorAvatar: "/manu.png",
    steps: [
      "Preheat the oven to 200°C.",
      "Boil the pasta until al dente.",
      "Prepare the pizza dough.",
      "Mix the pasta with the sauce and bake on the pizza dough.",
      "Serve with a garnish of basil.",
    ],
  },
  {
    id: "2",
    author: "Jane Smith",
    date: "4 October, 2024",
    title: "Spaghetti Carbonara",
    description: "A creamy delight for a cozy evening",
    level: "Medium",
    duration: "30 mins",
    calories: 450,
    image: "/recipes/spaghetti-carbonara.png",
    authorAvatar: "/avatars/jane.png",
    steps: [
      "Boil the spaghetti until al dente.",
      "Fry the pancetta in a pan.",
      "Whisk eggs with Parmesan cheese.",
      "Mix everything together with pepper and serve.",
    ],
  },
  {
    id: "3",
    author: "Mario Rossi",
    date: "5 October, 2024",
    title: "Classic Margherita Pizza",
    description: "A simple and timeless pizza",
    level: "Easy",
    duration: "25 mins",
    calories: 500,
    image: "/recipes/margherita.png",
    authorAvatar: "/avatars/mario.png",
    steps: [
      "Prepare the pizza dough.",
      "Spread tomato sauce over the dough.",
      "Add mozzarella and basil leaves.",
      "Bake in the oven for 15 minutes at 220°C.",
      "Serve with a drizzle of olive oil.",
    ],
  },
  {
    id: "4",
    author: "Anna Johnson",
    date: "6 October, 2024",
    title: "Vegetable Stir-Fry",
    description: "A quick and healthy option",
    level: "Easy",
    duration: "20 mins",
    calories: 300,
    image: "/recipes/stirfry.png",
    authorAvatar: "/avatars/anna.png",
    steps: [
      "Chop vegetables of your choice.",
      "Heat oil in a wok and add the vegetables.",
      "Stir-fry for 5 minutes.",
      "Add soy sauce and stir until evenly coated.",
      "Serve hot with rice or noodles.",
    ],
  },
  {
    id: "5",
    author: "Tom Brown",
    date: "7 October, 2024",
    title: "Beef Stroganoff",
    description: "A hearty classic with tender beef",
    level: "Medium",
    duration: "50 mins",
    calories: 700,
    image: "/recipes/beef-stroganoff.png",
    authorAvatar: "/avatars/tom.png",
    steps: [
      "Slice beef and sauté in a pan.",
      "Cook onions and mushrooms until soft.",
      "Add sour cream and mix with the beef.",
      "Simmer for 10 minutes and serve with rice.",
    ],
  },
  {
    id: "6",
    author: "Emily Davis",
    date: "8 October, 2024",
    title: "Chocolate Lava Cake",
    description: "Indulge in a rich molten center",
    level: "Hard",
    duration: "30 mins",
    calories: 450,
    image: "/recipes/chocolate-lava.png",
    authorAvatar: "/avatars/emily.png",
    steps: [
      "Melt chocolate and butter together.",
      "Whisk eggs and sugar, then fold in the melted chocolate.",
      "Pour the batter into ramekins.",
      "Bake for 12 minutes and serve immediately.",
    ],
  },
  {
    id: "7",
    author: "Chris Taylor",
    date: "9 October, 2024",
    title: "Chicken Tikka Masala",
    description: "A flavorful Indian classic",
    level: "Medium",
    duration: "1 hour",
    calories: 600,
    image: "/recipes/tikka-masala.png",
    authorAvatar: "/avatars/chris.png",
    steps: [
      "Marinate chicken in yogurt and spices.",
      "Grill the chicken until cooked.",
      "Prepare the masala sauce with tomatoes and cream.",
      "Add the grilled chicken to the sauce and simmer for 15 minutes.",
      "Serve with naan or rice.",
    ],
  },
  {
    id: "8",
    author: "Laura White",
    date: "10 October, 2024",
    title: "Caesar Salad",
    description: "A fresh and crunchy salad",
    level: "Easy",
    duration: "15 mins",
    calories: 350,
    image: "/recipes/caesar-salad.png",
    authorAvatar: "/avatars/laura.png",
    steps: [
      "Toss romaine lettuce with Caesar dressing.",
      "Add croutons and Parmesan cheese.",
      "Top with grilled chicken, if desired.",
      "Serve chilled.",
    ],
  },
  {
    id: "9",
    author: "David Clark",
    date: "11 October, 2024",
    title: "Grilled Salmon with Lemon",
    description: "A light and zesty dish",
    level: "Easy",
    duration: "25 mins",
    calories: 400,
    image: "/recipes/grilled-salmon.png",
    authorAvatar: "/avatars/david.png",
    steps: [
      "Season the salmon with salt and pepper.",
      "Grill the salmon for 5-6 minutes on each side.",
      "Squeeze fresh lemon juice over the salmon.",
      "Serve with a side of steamed vegetables.",
    ],
  },
  {
    id: "10",
    author: "Sophia King",
    date: "12 October, 2024",
    title: "French Onion Soup",
    description: "A warm, comforting bowl of flavor",
    level: "Medium",
    duration: "1 hour",
    calories: 500,
    image: "/recipes/french-onion-soup.png",
    authorAvatar: "/avatars/sophia.png",
    steps: [
      "Caramelize onions in a pot over low heat.",
      "Add beef broth and thyme, then simmer for 30 minutes.",
      "Pour the soup into bowls and top with a slice of baguette.",
      "Sprinkle with Gruyère cheese and broil until golden.",
    ],
  },
];
